server.port=${SERVER_PORT:9000}
cors.allowed-origins=${FRONTEND_URL:http://localhost:5999,http://localhost:5173,http://localhost:5174,http://localhost:5175,https://ywmarket.duckdns.org}

# Email setup
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=yong-1@naver.com
spring.mail.password=***REMOVED***
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true